# File: playbooks/xray_setup.yml
---
- name: Install and configure Xray
  hosts: vm_my_ru2
  become: true
  become_method: sudo
  gather_facts: true

  vars_files:
    - "xray/defaults/secrets.yml"                    # Xray secrets (UUID, reality keys и т.п.)

  roles:
    - role: srv_prepare
      tags:
        - srv_prepare
    - role: xray
