---
- name: Deploy Raven-subscribe
  hosts: vm_my_srv
  become: true
  gather_facts: true

  vars_files:
    - "xray/defaults/secrets.yml"           # xray_vless_client_encryption, xray_inbound_tags
    - "raven_subscribe/defaults/secrets.yml"

  roles:
    - role: raven_subscribe
