---
- name: Nginx frontend | Validate
  ansible.builtin.import_tasks: validate.yml
  tags: always

- name: Nginx frontend | Install packages
  ansible.builtin.import_tasks: install.yml
  tags: nginx_frontend_install

- name: Nginx frontend | Deploy HTTPS config
  ansible.builtin.import_tasks: nginx_ssl.yml
  tags: nginx_frontend_ssl

- name: Nginx frontend | Configure TCP stream relay
  ansible.builtin.import_tasks: stream.yml
  tags: nginx_frontend_stream
