---
- name: Nginx frontend | Deploy HTTPS config
  ansible.builtin.template:
    src: nginx/https.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ nginx_frontend_domain }}.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Reload nginx
