---
- name: Nginx frontend | Validate required vars
  ansible.builtin.assert:
    that:
      - nginx_frontend_domain is defined
      - nginx_frontend_domain != ''
      - nginx_frontend_certbot_email is defined
      - nginx_frontend_certbot_email != ''
    fail_msg: >-
      nginx_frontend_domain and nginx_frontend_certbot_email must be set in secrets.yml.
    success_msg: "Nginx frontend vars are valid"
