---
- name: Relay | Install nginx and certbot
  ansible.builtin.apt:
    name:
      - nginx
      - libnginx-mod-stream
      - certbot
      - python3-certbot-nginx
    state: present
    update_cache: true

- name: Relay | Ensure nginx is enabled
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: started
