---
- name: sing-box | Display OS information
  ansible.builtin.debug:
    msg: "Operating System: {{ ansible_facts['distribution'] }} {{ ansible_facts['distribution_version'] }}"
  tags: always

- name: sing-box | Validate
  ansible.builtin.import_tasks: validate.yml
  tags: always

- name: sing-box | System tuning
  ansible.builtin.import_tasks: system.yml
  tags: singbox_system

- name: sing-box | Install
  ansible.builtin.import_tasks: install.yml
  tags: singbox_install

- name: sing-box | Configure
  ansible.builtin.import_tasks: config.yml
  tags: singbox_config

- name: sing-box | Service
  ansible.builtin.import_tasks: service.yml
  tags: singbox_service
