---
- name: Restart xray-exporter
  ansible.builtin.systemd:
    name: "{{ xray_exporter_service_name }}"
    state: restarted
    daemon_reload: true
  when: ansible_facts['service_mgr'] == "systemd"

- name: Restart node_exporter
  ansible.builtin.systemd:
    name: "{{ node_exporter_service_name }}"
    state: restarted
    daemon_reload: true
  when: ansible_facts['service_mgr'] == "systemd"

- name: Restart xray-stats-exporter
  ansible.builtin.systemd:
    name: "{{ xray_stats_exporter_service_name }}"
    state: restarted
    daemon_reload: true
  when: ansible_facts['service_mgr'] == "systemd"

- name: Restart victoriametrics
  ansible.builtin.systemd:
    name: "{{ victoriametrics_service_name }}"
    state: restarted
    daemon_reload: true
  when: ansible_facts['service_mgr'] == "systemd"

- name: Restart grafana
  ansible.builtin.systemd:
    name: "{{ grafana_service_name }}"
    state: restarted
    daemon_reload: true
  when: ansible_facts['service_mgr'] == "systemd"

- name: Restart blackbox-exporter
  ansible.builtin.systemd:
    name: "{{ blackbox_service_name }}"
    state: restarted
    daemon_reload: true
  when: ansible_facts['service_mgr'] == "systemd"

- name: Restart xray-stats-exporter-bridge
  ansible.builtin.systemd:
    name: "{{ xray_bridge_stats_exporter_service_name }}"
    state: restarted
    daemon_reload: true
  when: ansible_facts['service_mgr'] == "systemd"

- name: Restart vmagent
  ansible.builtin.systemd:
    name: "{{ vmagent_service_name }}"
    state: restarted
    daemon_reload: true
  when: ansible_facts['service_mgr'] == "systemd"

- name: Restart xray-exporter-bridge
  ansible.builtin.systemd:
    name: "{{ xray_bridge_exporter_service_name }}"
    state: restarted
    daemon_reload: true
  when: ansible_facts['service_mgr'] == "systemd"
